### ISSUE TITLE
Hard-coded filenames

### ISSUE THREAD

**Issue by jepegit** [jepegit/coffeshop#1]
Hi Asbjørn,

Just for fun; created an issue on github on the hard-coded windows-path filenames in `schedule_tester.py`.

Proposed solution:
Replace

> schedule_filename = r"test_schedules\1_Standard_3cyc_C20R3-C50R4lith_30cyc_C4R3.sdu"

with

> import pathlib
> schedule_path = pathlib.Path("test_schedules")
> schedule_filename = schedule_path / "1_Standard_3cyc_C20R3-C50R4lith_30cyc_C4R3.sdu"

(and the same for the log-file)

**Comment by jepegit** [comment]
Another issue (when running on Mac):

Reading the schedule file using only `open(filename)` throws a bytes error. 

Possible solution; replace:

```python
f = open(filename)
for line in f.readlines:
    do stuff
    ...
f.close()
```
with

```python
with open(filename, 'rb') as f:
    for line in f.readlines:
       try:
            line = line.decode('utf-8')
            do stuff
            ...
      except UnicodeDecodeError as e:
            print(f"error in line:\n {f}")
            print(e)
```

**Comment by asbjorul** [comment]
Suggested changes have been made. Issue resolved.
